In [1]:
# Load the csv as a pandas dataframe
import pandas as pd

file = "hyperparam_results/encoderdecoderlstm_hyperparam_results_seqlen_modelhiddensizes_numlayers.csv"

df = pd.read_csv(file)

display(df)

,model_type,batch_size,sequence_length,model_hidden_size,learning_rate,num_layers,fc_hidden_sizes,val_loss,val_mae
0,EncoderDecoder,32,2,4,0.005,1,64,11184.786948,62.701204
1,EncoderDecoder,32,2,16,0.005,1,64,10662.621363,61.036078
2,EncoderDecoder,32,2,32,0.005,1,64,10227.419685,59.559888
3,EncoderDecoder,32,16,4,0.005,1,64,8239.241182,54.763806
4,EncoderDecoder,32,16,16,0.005,1,64,8007.533197,53.538555
5,EncoderDecoder,32,16,32,0.005,1,64,7972.115015,53.477589
6,EncoderDecoder,32,30,4,0.005,1,64,9142.658525,55.045532
7,EncoderDecoder,32,30,16,0.005,1,64,8599.521671,53.055687
8,EncoderDecoder,32,30,32,0.005,1,64,8488.305307,52.382460
9,EncoderDecoder,32,2,4,0.005,5,64,11213.606122,63.123096
10,EncoderDecoder,32,2,16,0.005,5,64,10319.153806,59.777854
11,EncoderDecoder,32,2,32,0.005,5,64,10013.432618,58.321014
12,EncoderDecoder,32,16,4,0.005,5,64,8234.557545,54.895260
13,EncoderDecoder,32,16,16,0.005,5,64,8076.612346,54.281078
14,EncoderDecoder,32,16,32,0.005,5,64,8091.594463,53.815736
15,EncoderDecoder,32,30,4,0.005,5,64,23043.820569,98.719857
16,EncoderDecoder,32,30,16,0.005,5,64,23034.496747,98.922009
17,EncoderDecoder,32,30,32,0.005,5,64,23030.351437,99.021087

# Top 20 results based on val_mae:

In [2]:
# Sort the dataframe by the 'val_mae' column in ascending order

df_sorted_mae = df.sort_values(by='val_mae', ascending=True)
# Display the top 20 rows of the sorted dataframe
print("Top 20 rows sorted by val_mae:")
display(df_sorted_mae.head(20))

Top 20 rows sorted by val_mae:

,model_type,batch_size,sequence_length,model_hidden_size,learning_rate,num_layers,fc_hidden_sizes,val_loss,val_mae
8,EncoderDecoder,32,30,32,0.005,1,64,8488.305307,52.382460
7,EncoderDecoder,32,30,16,0.005,1,64,8599.521671,53.055687
5,EncoderDecoder,32,16,32,0.005,1,64,7972.115015,53.477589
4,EncoderDecoder,32,16,16,0.005,1,64,8007.533197,53.538555
14,EncoderDecoder,32,16,32,0.005,5,64,8091.594463,53.815736
13,EncoderDecoder,32,16,16,0.005,5,64,8076.612346,54.281078
3,EncoderDecoder,32,16,4,0.005,1,64,8239.241182,54.763806
12,EncoderDecoder,32,16,4,0.005,5,64,8234.557545,54.895260
6,EncoderDecoder,32,30,4,0.005,1,64,9142.658525,55.045532
11,EncoderDecoder,32,2,32,0.005,5,64,10013.432618,58.321014
2,EncoderDecoder,32,2,32,0.005,1,64,10227.419685,59.559888
10,EncoderDecoder,32,2,16,0.005,5,64,10319.153806,59.777854
1,EncoderDecoder,32,2,16,0.005,1,64,10662.621363,61.036078
0,EncoderDecoder,32,2,4,0.005,1,64,11184.786948,62.701204
9,EncoderDecoder,32,2,4,0.005,5,64,11213.606122,63.123096
15,EncoderDecoder,32,30,4,0.005,5,64,23043.820569,98.719857
16,EncoderDecoder,32,30,16,0.005,5,64,23034.496747,98.922009
17,EncoderDecoder,32,30,32,0.005,5,64,23030.351437,99.021087

# Top 20 results based on val_mse

In [3]:
# Sort the dataframe by the 'val_mae' column in ascending order

df_sorted_mse = df.sort_values(by='val_loss', ascending=True)
# Display the top 20 rows of the sorted dataframe
print("Top 20 rows sorted by val_mse:")
display(df_sorted_mse.head(20))

Top 20 rows sorted by val_mse:

,model_type,batch_size,sequence_length,model_hidden_size,learning_rate,num_layers,fc_hidden_sizes,val_loss,val_mae
5,EncoderDecoder,32,16,32,0.005,1,64,7972.115015,53.477589
4,EncoderDecoder,32,16,16,0.005,1,64,8007.533197,53.538555
13,EncoderDecoder,32,16,16,0.005,5,64,8076.612346,54.281078
14,EncoderDecoder,32,16,32,0.005,5,64,8091.594463,53.815736
12,EncoderDecoder,32,16,4,0.005,5,64,8234.557545,54.895260
3,EncoderDecoder,32,16,4,0.005,1,64,8239.241182,54.763806
8,EncoderDecoder,32,30,32,0.005,1,64,8488.305307,52.382460
7,EncoderDecoder,32,30,16,0.005,1,64,8599.521671,53.055687
6,EncoderDecoder,32,30,4,0.005,1,64,9142.658525,55.045532
11,EncoderDecoder,32,2,32,0.005,5,64,10013.432618,58.321014
2,EncoderDecoder,32,2,32,0.005,1,64,10227.419685,59.559888
10,EncoderDecoder,32,2,16,0.005,5,64,10319.153806,59.777854
1,EncoderDecoder,32,2,16,0.005,1,64,10662.621363,61.036078
0,EncoderDecoder,32,2,4,0.005,1,64,11184.786948,62.701204
9,EncoderDecoder,32,2,4,0.005,5,64,11213.606122,63.123096
17,EncoderDecoder,32,30,32,0.005,5,64,23030.351437,99.021087
16,EncoderDecoder,32,30,16,0.005,5,64,23034.496747,98.922009
15,EncoderDecoder,32,30,4,0.005,5,64,23043.820569,98.719857

# Aggregate results for each hyperparameter combination by taking the average of val_mae of grouped rows for:

In [5]:
# Range of hyperparameters:

sequence_lengths = [2, 16 ,30]
model_hidden_sizes = [4, 16, 32]
num_layers = [1, 5]

## Sequence Length

In [4]:
# Group the dataframe by 'learn_rate' and calculate the mean of 'val_mae' and 'val_loss'
grouped_df = df.groupby('sequence_length')[['val_mae', 'val_loss']].mean().reset_index()

# Sort the grouped dataframe by 'val_mae' in ascending order
grouped_df_sorted_mae = grouped_df.sort_values(by='val_mae', ascending=True)
# Display the sorted grouped dataframe
display(grouped_df_sorted_mae)

   sequence_length    val_mae      val_loss
1               16  54.128671   8103.608958
0                2  60.753189  10603.503424
2               30  76.191105  15889.859043

## Model Hidden Sizes

In [6]:
grouped_df_model_hidden_sizes = df.groupby('model_hidden_size')[['val_mae', 'val_loss']].mean().reset_index()
# Sort the grouped dataframe by 'val_mae' in ascending order
grouped_df_model_hidden_sizes_sorted_mae = grouped_df_model_hidden_sizes.sort_values(by='val_mae', ascending=True)
# Display the sorted grouped dataframe
display(grouped_df_model_hidden_sizes_sorted_mae)

   model_hidden_size    val_mae      val_loss
2                 32  62.762962  11303.869754
1                 16  63.435210  11449.989855
0                  4  64.874793  11843.111815

## Num of Layers of Encoders and Decoders:

In [7]:
grouped_df_num_layers = df.groupby('num_layers')[['val_mae', 'val_loss']].mean().reset_index()
# Sort the grouped dataframe by 'val_mae' in ascending order
grouped_df_num_layers_sorted_mae = grouped_df_num_layers.sort_values(by='val_mae', ascending=True)
# Display the sorted grouped dataframe
display(grouped_df_num_layers_sorted_mae)

   num_layers    val_mae      val_loss
0           1  56.173422   9169.355877
1           5  71.208555  13895.291739

# Conclusion

Optimal Hyperparameters for Encoder-Decoder LSTM models:
- Sequence Length: 16
- LSTM Hidden Size: 32
- Num of LSTM layers: 1